/*------------------------------------------------------------------------------------------------------------------------------
//                   __     ___      _               _     ___           _ _ _                                
//                   \ \   / (_)_ __| |_ _   _  __ _| |   / _ \ ___  ___(_) | | ___  ___  ___ ___  _ __   ___ 
//                    \ \ / /| | '__| __| | | |/ _` | |  | | | / __|/ __| | | |/ _ \/ __|/ __/ _ \| '_ \ / _ \
//                     \ V / | | |  | |_| |_| | (_| | |  | |_| \__ \ (__| | | | (_) \__ \ (_| (_) | |_) |  __/
//                      \_/  |_|_|   \__|\__,_|\__,_|_|   \___/|___/\___|_|_|_|\___/|___/\___\___/| .__/ \___|
//                                                                                                |_|
//
// File:   plotBox.hpp
//
// Author: Silvano Catinella <catinella@yahoo.com>
//
// Description:
//
//
------------------------------------------------------------------------------------------------------------------------------*/
#include "plotBox.hpp"
#include <QVBoxLayout>
#include <QLabel>
#include <QFrame>
#include <QPainter>
#include <mainWindow.hpp>

plotBox::plotBox(QWidget *parent) : QWidget(parent) {
}

void plotBox::rebuildGrid() {
	//
	// Description:
	//	This method draw the oscilloscope display's grid. As in a real instrument the grid is fixed
	//
	gridLayer = QPixmap(size());
	gridLayer.fill(Qt::black);
	
	QPainter p(&gridLayer);

	int centerY = height() / 2;
	int centerX = width() / 2;

	// Right side
	for(int x = centerX; x < width(); x += PLOTBOX_XGRIDSCALE) {
		if ((x-centerX) % 50 == 0 || x == centerX)
			p.setPen(QColor(70,70,70));
		else
			p.setPen(QColor(35,35,35));
		p.drawLine(x, 0, x, height());
	}
	
	// Left side
	for(int x = centerX; x > 0; x -= PLOTBOX_XGRIDSCALE) {
		if ((centerX-x) % 50 == 0 || x == centerX)
			p.setPen(QColor(70,70,70));
		else
			p.setPen(QColor(35,35,35));
		p.drawLine(x, 0, x, height());
	}

	// Up side
	for(int y = centerY; y < height(); y += PLOTBOX_YGRIDSCALE) {
		if ((y-centerY) % 50 == 0 || y == centerY)
			p.setPen(QColor(70,70,70));
		else
			p.setPen(QColor(35,35,35));
		p.drawLine(0, y, width(), y);
	}

	// Bottom side
	for(int y = centerY; y > 0; y -= PLOTBOX_YGRIDSCALE) {
		if ((centerY-y) % 50 == 0 || y == centerY)
			p.setPen(QColor(70,70,70));
		else
			p.setPen(QColor(35,35,35));
		p.drawLine(0, y, width(), y);
	}
}

void plotBox::resizeEvent(QResizeEvent *) {
	//
	// Description:
	//	This signal is generated by plotBox's window resized event. plotBox advise everyone its displayed data can be no
	//	more coerent and it needs new updated data. This signal is trapped by mainWinow
	//
	rebuildGrid();
	emit resized();
	//update();
}

void plotBox::paintEvent (QPaintEvent *) {
	//
	// Description:
	//	This method overrides the parent's virtual inherited method. It draws the object everytime the
	//	parent object is redrawed
	//
	QPainter p(this);
	if (gridLayer.isNull()) rebuildGrid();
	p.drawPixmap(0, 0, gridLayer);
	draw();
}

void plotBox::setXScale (int value) {
	xScale = value;
	update();
}

void plotBox::setYScale (int value) {
	yScale = value;
	update();
}

void plotBox::setDataPool (QVector<QVector<double>> &visibleData, QVector<bool> sigSelect) {
	dataPool = visibleData;
	channelMap = sigSelect;
	update();
}

void plotBox::draw() {
	QPainter painter(this);
	QColor   color;
	
	painter.setPen(Qt::green);
	
	const int yZero = height()/2;
	
	for (int x=0; x<dataPool.size(); x++) {
		//qDebug() << dataPool[x][0];
		if (x > 0 && dataPool[x-1].isEmpty() == false && dataPool[x].isEmpty() == false) {
			for (int w=0; w<dataPool[x].size(); w++) {
				if (channelMap.size() != dataPool[x].size() || channelMap[w] == true) {
					color = channelColors[w];
					painter.setPen(channelColors[w]);
					painter.drawLine(x - 1, yZero - dataPool[x - 1][w], x, yZero - dataPool[x][w]);
				}
			}
		}
	}
}

